# Generated by Django 5.1.2 on 2024-10-23 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('Primary 1', 'Primary Year 1'), ('Primary 2', 'Primary Year 2'), ('Primary 3', 'Primary Year 3'), ('Primary 4', 'Primary Year 4'), ('Primary 5', 'Primary Year 5'), ('Primary 6', 'Primary Year 6'), ('Prep 1', 'Prep Year 1'), ('Prep 2', 'Prep Year 2'), ('Prep 3', 'Prep Year 3'), ('Secondary 1', 'Secondary Year 1'), ('Secondary 2', 'Secondary Year 2'), ('Secondary 3', 'Secondary Year 3')], max_length=20)),
                ('learning_type', models.CharField(choices=[('Visual', 'Visual'), ('Auditory', 'Auditory'), ('Kinesthetic', 'Kinesthetic'), ('Reading/Writing', 'Reading/Writing')], max_length=20)),
                ('first_time_login', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('major', models.CharField(blank=True, choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Engineering', 'Engineering')], max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
